name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      COMPOSE_INTERACTIVE_NO_CLI: 1
    steps:
      - uses: actions/checkout@v2

      - name: Cache API composer
        uses: actions/cache@v2
        with:
            path: /vendor
            key: composer-${{ hashFiles('api/composer.lock') }}

      - name: Init project
        run: make init

      - name: Run tests
        run: make test